### ISSUE TITLE
添加几个数据集来做完全多视图的对比实验

### ISSUE THREAD

**Issue by zhangyuanyang21** [XLearning-SCU/2022-TPAMI-DCP#1]
你好，林老师，请问怎么修改代码添加几个数据集来做完全多视图的对比实验呢？

**Comment by Lin-Yijie** [comment]
您好，感谢对我们工作的关注！

需要修改数据集读取和参数配置：在utils/[datasets.py](https://github.com/XLearning-SCU/2022-TPAMI-DCP/blob/main/utils/datasets.py)里写改数据集读取，configure/[configure_clustering.py](https://github.com/XLearning-SCU/2022-TPAMI-DCP/blob/main/configure/configure_clustering.py)里添加对应数据集超参，[run_clustering_multiview.py](https://github.com/XLearning-SCU/2022-TPAMI-DCP/blob/bfece1d4603c2793b2bb48bdfd4bbf33b43fbc74/run_clustering_multiview.py#L17)里也需要添加对应数据集信息，执行如下运行指令时设置missing_rate 0 即是完全多视图聚类。
python run_clustering.py --dataset ？ --devices 0 --print_num 100 --test_time 5 --missing_rate 0
