### ISSUE TITLE
关于代码中的type

### ISSUE THREAD

**Issue by ChenyuxinXMU** [XLearning-SCU/2022-TPAMI-DCP#2]
您好，
      我想请教一个问题。
      在此代码的多视图聚类版本（run_clustering_multiview.py）中，出现了config['type'] == 'CG'（CV），这里的CV和CG在处理细节上有何不同呢？如果使用的是普通的一维特征数据（非图像），该选择哪种type呢？

**Comment by ChenyuxinXMU** [comment]
很抱歉，我在详细看过您的文章之后已经了解了TYPE的含义。再次感谢！

**Comment by Lin-Yijie** [comment]
感谢您的关注！

Core view方案在实现时会更高效，两种方案的效果其实差异没有太大。
